language: ruby

rvm:
  - 1.9.3
  - jruby-19mode
  - 1.8.7

before_script:
 - mkdir ~/.task
 - echo data.location=~/.task > ~/.taskrc

before_install:
 - echo | sudo add-apt-repository ppa:ultrafredde/ppa
 - sudo apt-get update
 - sudo apt-get install task
